[package]
name = "bob"
version = "0.3.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-abi = "0.11"
canonical = "0.7"
canonical_derive = "0.7"
rusk-abi = { path = "../../../rusk-abi", features = ["module"] }
