[package]
name = "transfer-contract-types"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-bls12_381 = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-jubjub = { version = "0.14", default-features = false, features = ["rkyv-impl"] }
dusk-poseidon = { version = "0.33", default-features = false, features = ["rkyv-impl", "alloc"] }
phoenix-core = { version = "0.26", default-features = false, features = ["rkyv-impl", "alloc"] }
rkyv = { version = "0.7", default-features = false,  features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
