[package]
name = "transfer-contract-types"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-plonk = { version = "0.13", default-features = false, features = ["rkyv-impl", "alloc"] }
dusk-pki = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
dusk-bls12_381 = { version = "0.11", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
phoenix-core = { version = "0.18", default-features = false, features = ["rkyv-impl"] }
dusk-poseidon = { version = "0.28", default-features = false, features = ["alloc"] }
nstack = { version = "0.16", default-features = false }
rusk-abi = { path = "../../rusk-abi" }

rkyv = { version = "0.7", default-features = false, features = ["alloc"] }
bytecheck = { version = "0.6", default-features = false }

[features]
default = ["host"]
host = ["rusk-abi/host"]
