[acl.stake]
owners = [
    'mvft6AXjR1mDtg1Qo3GzGBKZAvvxY1S6h41DSEPh9Ewj9GFR61rPQnjVaM1W9nqkHijRC2d5Yo4FSBwU8wf9eHeEJYXuMSrB7eJxvsY6HjCeDJ9pKfJLdjayAfrxEyudvx2',
]
allowlist = [
    'pFPEcfxidLvwmFKRQoifrSyWmmVY9UDEThoRFvGXddXRLZ8hB7xfWDYQYwHhTvZvXeL1p5Ygcnsuuxm1X8nHFJH6tEgK3cS76squcFVFSejaKJGMorYZdTup5uscNq6eDU2',
    'rvXLHF8DBNwzZ63uSWPki3y7uNgGbdRCrKpouEP9N7awiGBDaP1uzyrtLBDtFbNgw8bPNjbyMsfAsNutZKnuX8JXzMiFvpW9vK4c2zmAmk3RygzwiFGCVJ9KSU7b4bgC1UT',
    'rdHa4H5p1rVtQyqD5AjDHyr1EGg7yVU1wynqQ9VRqU8Wp7kMcePsSk2tURGzRLnzS36CaKEadpfRGwa3ucvFH5MEGYvF1LAqSQQT3zE1Fx7wQzYsrvDpJ44bBa6dKxN6mTC',
    '244Sywxj7PuMHpcPxemaXLcrY5rPgztra6H9Vz8cU1Ro5v23SxKTfVqr2yS7NXAXE1iq59ndn4aMZmYxuzu3Te3e9fokQKTUkYvFxYg2P2E8EEg1gWUbs3AFL2aNx62HQd7r',
    '24bfNr8MDUo5xJBecmeGzXDEraax4Cmbnhjyyt5GaL1Vbe6H48ZSYTpmjRDcFRDFzgzuePAPUNcdGMnBzBQBk4zAMgBCtPsY27tBJtKmB1st6qcmpzRR4Er5imxrzvMRnfWc',
    'xEXp8qBarpXnVD9DJHUj8ywkWPggbPmgsmGFFtGAuXd2EXwEiXiXJ6r4WqdjvTvpE7Fx42TpwnkrpFwdc5BphPu7LCQ3FPU1DMQ1WKoDCxeQVircgHKrFpWsCZ8VLrGCdWm',
    'shAky1Dnjxdhy1HsJRC17hgFw7YmT8PSdobce73k3ANmJWaDmycRyqruoxoxKoaVpudkCY4ENSgrkEoUgfG9xBa77jULgpDcWvYNLFQfWsA2bSFbooCJhZTHyGLyNQC73os',
    'uDYKaU8SM5iriU88tWsR8Z7KbepmjiVubFLtetASuzEeBjwJZ5en4XuXjJTCZgHztK85gjS9que8njCebHGku9wnXzKbneYwx5xF1puiNF8XWRTcvDAta1ndsa4jAqGkWzm',
    'zVnmVA7jfgAoBGnsMDrHGiwPx3sZhG42t6pysHjMj7rF6BKPGut87GZaDaXwmdjXsz53ULB2Mmur9aoSU1ZCGHYwQ57eN59FMwHqdBjULpNBfvFZN1qnzVpgz23y3UPPz6x',
    'shB6W4UWipm3JQQgmbkC4Xy3CEvtyz4FL3QBpYUb5aRr4UspY4ezzq6XzoYENZgaf6p2j3xrtLuWNGcYhNU1jUdi9hS62bvCctoiqNNVdx1dXLJHyndHyT97Cww6Kmyr5r9',
    'prV8r1A5oHHyMGuqvsyVP4eMfaqbYYtzKvfV6phwHMBNKaDnRCy4ntC81QGGS1dUDyqu6EuNamAEHZpR5cWWQkHvABrADkXs1fDbNqKtisEAnVjBj46iDJdQ7ck4vGs69Td',
    'qHeUtHGi27ZRFHyBimKF6fHCy8B3mr2VShAkfk2ifkb8HAwD8Gr7Zrq96F9s5G4VWFUSbaUVcCBnExnumHeoQqfjRp52CRfzXDzkBevUG2CVtGqUvGGV1DxsDAEXHhCyXbX',
    'sMnHcRLM2BTKDLrJUDcTQPAE7NhkNDS3v986rmV2eZJF5RRqtDJQya2RnLTN8vBodfHrqxVeVpFG2MEbta6YmNfokSn135rYhAvnmDwPL1nd3Uq3iwqih5hNBpiGK7HY9D1',
    'oUgxBUWEPyFAekXW9T2UdJBcMF7xAuBfstrCX8ATXFk7MusqddFGoq2LN9euCbwVuXpSM5rGLKNUb6NVPFUVM5g4pA6CnXjNfNVBiy91NcH9eBVcdcG1eYUaKWQSYQ9t2um',
    '26brdzqNXEG1jTzCubJAPhks18bSSDY4n21ZW6VLYkCv6bBUdBAZZAbn1Coz1LPBYc4uEekBbzFnZvhL9untGCqRamhZS2cBV51fdZog3qkP3NbMEaqgNMcKEahAFV8t2Cke',
    '2681cRrpmrN17r1C1jNKNqAL6xc7mCTNu9qwhtjTVNHiaVioqowCcTcMqXcmYuqpG8c22bPqKWDRfRmzcfSnLLA9GG5jdgBhmoQxSAqaXMUL2Ee5LAGMB5RJycuUcDoHTCwY',
    'nV71a9Hec6jeXVFkUN6JvgiLDTucp1R4g6GewvnL7nYLbRrcxuPtFHt2PNjApDaLXLKTBEEwMdefjnQgKtBFaJAtA1jxkF9K2EKW1nBea26cHcvb326rbXNgYA4pNWv4roh',
    '26LsKrN6Rk4UPALU6msRjkdu5tdSsoNtudcMSvz8Xa2jmp6gDCv964yf7rq4SC4bHDCuoT28KBS8989WfTjBuxTdYqQhCswDL1MiDhXBvraiWPX9Hjhvi1X4pbs757sHYXGb',
    'uSXgfWF1uhmxjmLaQPXhVY2NJt1UNUKf5xTGK5eCGF1kFtnhG2DwhYJGX4kowZScrJV37vEFDMPEzG4q2hsjBoSMbnMjz7qUWevKA5UP3MBZS45k6vcjHEF5GB5CeuafQwA',
    'nvdsjA8biVgXQc7fFYxJwZAY7AM1wc8YqYNQ5fFe8NYQZnVHSRny6yQadz5MNXzsCYhcFHDAGqrgVRDKoPNN41Z2bwy57SZwCXSBrx3SnjVbefrRXzXAEuHMfUEBBtq8gzH',
    'm6dy2gz3jC3ifLpZmdTaZbgcptWxRrfnQEZ8hG8ewhopKXTcCTnTqs4UeucXFkcSuFMfTqMzT1Go6KfNkuFvJPvsrvp5vKxEccuJNUgMi1uSCne1ti5kgYeNHtW82FWtnpf',
    '26DsWXiCrNxkmCZ1zfCh3XTE2cXqf4NEPGGRMU39vZhNYF6hExrRrzN4nETVYduLuiRAHmtonkP6TvtVnhf9v5YcksgUfhHY78dNgCTSZs9WgHjN4NP2QRiybAaH3xUGeatm',
    '23fAnih3A9TtZLmwBggRgjGHsEB9qyVTq25C1LahSVH2LigFdjLxveccFgnfQPxWUmMFLJDh8Ptd4NivosEK6pDZoAb48EirBaKqDEExh75iXDsr6k8hjFxV2hJhfGtYLFGr',
    'yDiwuTDWV9WPeihhaToqHYijiwM5n84deh8Nn779WyNr9kGFcRLnHHkDTcVpzLaNSEa7b3DQQky6i72hvsrKJ2uFSsJQD37pokQKVokV4Q2q1p1aRPNRdSujfmcdMP3MBVS',
    'txesrFKYx2Ea7foBoBUNDj1rn1MjG8KREfZYNEb6UGg1k3KSBQdXr52Ayfemz1cEJ64AosipuGH5khnSXq87EcKP6uD2JrGb1NKdAgBELYkocXpbcmANd4VupWnVCPoecr1',
    '24Qzcp49pQt8Rb1bWf65Yq76QysTfyQKUZh7C219345iD6eYfHKptxxAKrqGYLFXKUci3NR5FbLhFjmLnL4jf249hwZK19gY2nqKESbSyfkMVMQHpS5dVVcN2my1KWR3jha4',
    '26TVUnyxdYwX3Sipc2RLAwGnE6gLHW86sudf2HU3xP8S7NbAoiJDUE2XTn1FaEKV32FvZpCf9SjsgkYatddn6BsoBhMTmXyd1TMpzgFyJ8rGNXNN2R9LBuHfCXoXXj3MtNJr',
    'o6Ckan2efbGTbJRSgzM9vwK5z4fTY5AFr3WqWTRNVL8dsXxEBkEqa4wsHs6g3ARWZovFVEkV3r1HJZbhLWK2vC8xBarMRKifta7xZNeprb5xUFpjeS3ekF9VBsnKPbwTtP1',
    '23hcRjNqzKUhcHevbiP24NThLLbCjMXDFdwFXqgLjmx5cheXE6drSuSiuvvaSc7rbnbR2Yb1NY1x3276WVp47nFUM2ygmmERC4cxuF51aMqu75PVanouxfgmaHtFHjcHoHjj',
    '21SQ3HyThUvJUAtn3cfYUAisdw9h25DCp5hT2vzeiiQrvjGpmjsZKmbMMQTFSfU3EsEYtLqncXhVRkxnapwYrjYmR1tVdx3xE3nz2UkxSD1L34E1aTCoGqqZek9TfmSTQ5Sn',
    '26KjFyAKT9sMsASS2GTdrAgBswwwUvDAWwRdHWz2Hxp1BLa5VaD5LPAEPocHzsV4CEq3AM66qhUPAsB45FjsYzJB4wVU55ibUT3CNY8SxTgRfbVBpy5BSa4SDmZ7xff7cFJH',
    '26N7gdQRjgw9atu8nN5ua1bfxBp7kdNvE5BRHUvaMFGjwrNcRrDNedhK2RrqVooRJ8SMGi1iYiW4Wnysx4SMcbUPffwNeY4T1wQLt5ESdYjh91exuhR15S9c3o7Eu6EZNudz',
    '21kVjRYLmoPy3WGK8h2TrVxVYzWT5QZfpMD9JHwAALkAVbvGLGETJxPmZuMDZNLxXUkebsyCRXSzxgNAvoiMxaYX2mFwm6RnYHrg9z7iUV2uX3ZJwKk5oHHYvSvHtzdEhPka',
    'nkKb7ixLVJULE9WFufo5hb11Ggt9ako3tabHesmfTb1uDDHGscKKcSn4Cid8mbnFuRfJurrDwdi7ZPMUfDR5jkWMMC4GqBPaNU7Fka5LJhjQQmJVqmJXrbTMRMijWvB1p3Y',
    'sVmcJnhKJDfm8wzVjyeLhxi9RjcabEagJLnQoS6BXV6VvQ1GHpnyTPJBJbwCbG5igWn49UdMQtroxr2pGggh2FbXtyUbKqWexyK5LGgFn5QS4FesdFbnbcWf2bYkx6vDeDM',
    'oZR6eDvW1ZQeqqDeegV9eaWMsxmVeWkugNfisTNUkiD8ecHpQbEHPSn6knvCsjxS94t93Pig9JpjZ5zQrujdtWhJvFpGiLFWFpCThrJhCFpAa4jZjKkPwAZCwQSoeehg64r',
    'mgmcqkk1VFfsa1ko7ydBjhVuM9WuVFDGby9JthvDWsKX9kyqdNeqrSzbW1ccQ19sVfbHgVzfYwdGLipYdPcU4ZD5CjsbRmzZeEQ3WBZHUcEWDB1wsvV5avoC2xddxLvEDVP',
    '23gx8TwJPoTxFppny5Py7JwH5bGSFfZq5igPYDgoJEg2qhzVgXAsGKsspfB3yWY7k428dH2yhyoXM8LB4vzvRBXmdUsMpYhWc73yvsHaBkwQqcvrZzJRUF7zxEMP5DKVzAFJ',
    'pjsbtm6iNLBbMNG4FBGqggEFsiF8Y1DUUYb9J3KYeeQmoVUoSNfRhztzQQds2NLZYgWDGuXnQ3mLtZDK7MxNnQmEY98hdjfTWyGAigTRC9aizgF8WFo7it6ySQQ9fF9Rhea',
    '22exgqwRRtryBxVT7f7xC27fBkcHjUbAA3BxqL9ySqDguJAaWY5UWtgVkcm3o8HE1Tf8qcfXNpBt7ezva3pLSaygVrrdnRktF4stZMDoLnUhy2ej1hnoKP91TyQrumkbUU4n',
    'xqn4oFHyeUE46CJ7XZnaA6pFSqUt8EkoNjM1or4dyNigWpP9GfbH8Y5ps8PqCF5wcnfvjoBtM2gNrauB3EVATv6PnLPiGBp46eiNqrVcWWcFjNTwB5ggQ1cJQVdDXsoNi1S',
    'u1bee5K2ZFCDr7Cp1wZRomLHM18TVRwqtMNTFYX8dojJRQMEmALMVceKo6n5P29U3H7eNkGoTwV8aPdgt1tHSgoyHqkvKdGebNp8wa6EsqF1JU3mQFKVzUbeWt3wvuGm3Lk',
    'pSy8VbEwv2v3B75yVkYLYsVjxhYbpNbKDnYwnBbrfqNPfYGUWj6SfDwnx9BKA8QWMGZCnKqWVv37USgZoEJppXZe37rb4qeBodQ3vqXLEqw1F7VaFpvN89pzZYpBEqqiQG9',
    '25MjwFViKFCofcwqP9z7Em7hLzx9E9tou7tS9X3SDvzJvRWUixMZmHWQMDNnJZNN8PdzLBy9sj3wjscR4aADVNM7WqMnGfZxNdRAh4nWdW5wpAH8Dqn2hGTLE6kCUcKSMZE4',
    '23XeH9YWf68FhQX6wdHBjrdz4Yu2N9DuubrthX267FcdWaqPRyKwTnvYa2xRTaEJG2LBY96XzG4NRStHktt2ETZitSRN7ZjoKAe43EFKEZfCge4MCgoWYfMptWSqE9sZUzzE',
    'm9dVuRgr3CQX5P5Fxh2t68QRhRFBZFWroUM9Do77Xusc6ZuJHfj4xhPokm62bFXw8WrA2Lq7dkJcFSEGHKBvVxJ2TmZBJKBBjzhEXtCP7UmZ9qF734nJJhb2f94r33pFQyz',
    '24APW8dZ91iy4kwVAFAZ8rDRg8tZtLuurUB2aERXUKRj5tEMQQhTHQp2p5oxKtZNrpcWUKidK6u9tHTSZy9mzWnKtwu5Hnf1s42bdG4tcZw8edJPzePVWRytGoUXMHmuWWG3',
    '238cmghibzsNoAhVYsXfmmgv4MCN88PWQMcmUTSbvTXJ1uFpqi4ejo74eNZQnve1xbwiLREyo4p2kReH49vV6gi6Wf137chzfiCMoG18LHBkTVxrwxWEinAyeQmd2QiVitV8',
    'qXCkaKuFChiPXXzU8Zz4RHNAygDmHFBSbBiCFhtiqMtVXdhv7DbiUtFjoyaEFvfDuH2yJ92Lbbydyg1onghEi79HcVfMxwJksAFPJk3qgXFGutvWv5JCMPmujTkwY1MdMfv',
    '25KnsEoBhedA6Gnyx67c2i69h3iYJFErFdKVWZygVPgsyc7b5Hz1X6pP1NUREt9DQ9byVxkHtwmoG1Lhirr1QGG1vLLEd6AT8k5HWqZSisqvPexAzzxX63xCGwkW4ZiR2AhL',
    'oXYZWNZwxdDnd4e8qUE9gQUzcAZ1NzcBuhj9bjKi3kE7doyRJ4ixeoerFU8eM8v98C9gmFK2vJ67MdocCKKEexUXnoyyjUWYuNyoWQXJKGPK5EaZYo45Up2y2dqTG56KMqH',
    '24YhQRLs3Yv9ChjpwshFQAFqxmYNMzvFynpcGvEYXUCz33whjrQbX4yRvMwSTL5vEivpx8Enm8cxhDeGxXkQRrxtkzZ1WERnBLtz4JsBf6m5QmQzUziTKiofZnRHFRm5zQ1z',
    '26LZQDrSNPHgv5HkBdFhYr5TEm3y9zDwceotnywHg9Dproqd3yHymHZskEFxjSStfyyqNo1vvAF1h4nEXEy378W87EQ1p7EC9rfES65C6xGQDS7ujQCAPMoQBp3F6dopZk4i',
    'yomfztR36C81wr31uZ5XZFvww6dfcFK2wBmvRsHnm3JVgF3XcCz6fs58Z3hfiFswux55xsVznuwMRq6Frk28FcJRrpvnsyT3pRNmuqq4mHFqvPYbSYk75BnC3dJX3DD76pC',
    'xWeLQPyUXo82pjvxmf5iZdr5itR7kWriTpMK47M5KkDYYtg6Vmtgt1D5DLgEDLfv8BuJjyuB4aDB9wM3NXcdEY4Y9wzJ87JKjGfY2XzZVvb6R3LcxWCmzRfBS1bSihu9af7',
    'qe2tbCK8cBBwPLEwGNWmaJWx5cZ6Gkf4mUAdbPU16PMa7GkuMQFBg1JK77qXo8oQHhJM59Yr3xoSUdBKNgeQXGPybd13pyDWTNCjTXoa4fsg8G6nYb4vHKHngPy4fAg9WuA',
    'xLwzkFxrXetA74LSreTusgyv9Lh62tvHfL7jnuGmEdG7Aa9W7XLEDx7Ag968wjD8CyVncvsKVd6YXzrB6HdHVa1e7mYDVe6tDrmXiAatAnH3KphhPHzcPsEUQZzyhV2Emqt',
    '26zCm7Hqi4Gv42D39zx9p8tG1aHDuVRaYABpNGdmcusWJchmTRRHtagWFZo76SMyCUui3JvnFRNekNu6WShm6mW9F8uEucUau8H3cCpm1osc4gZLd8WaCaGzWV2gvt8dhyga',
    '25hHuGqH6MU67syGovZD2L1eEBypLb7fCV2Q7inVWSYSWqto9Yr962rfsUjL5WZjGBwa9EkFf7eBcouKRKNvhYrm7LPRQk6k4JR45KtnKUjXgdDTsmYJ4G49V4o3pT5aGdMP',
    'qWpfeFB4BB6RLCWdAaeHcq84BfeXKFh3woQFUCGc2wnCMyh5bnzofBMxm63Ns6fe6QuFUmRj7reyJVy958pwb9h4yCh97QfkKvmgtdyDxamD1UkeX9Y55wRGTSgdugosLLc',
    'nXqyaSYaTas47KNqNwVtpNyfCsTmvYMQ2bXcmtpVbiuMLn9NsE7SwsJFq1bLh9jtwRSN7Wkg7h53DV1DSdEPnD3dwsMxy4hmYaiRmeqGw9z6tpqYcyaGWjURkQpLqoCPDeD',
    'zT3G39wGo9htH5GGCfugrE6fEbpDknb2aNwrPS51Upiqb1zZh8QvJKDKJjrJYC9fNBwezUWbqiN1HXjr2kzcQYacXQkyycVqP88aHb7v6RNCuLuPVEF8iMpZGEteeRXb2nS',
    'y2axcZATs557zYzuuQSyyVDpV7jxR5th4YFy22o7bABByvXvybTGCUxfvsyaSsenZA5b1sYYdSLwYdjttnkx9wBpYhuTqy72xKSKhbJFwZwzmUEkpKCwT6pRXqgDV2BBFvC',
    '24TMiKLMRMv8BJFoGxHGVcHQoqkoEhcEAFDvBmM6iQ6TK3oyeiXSTYdQZSvad8AYaQcfvLSetJg2urFtDJJu5WgakYoXzm2HdwuotouiFCBdWsKe8dVhZgN7ERYhcxKr7LTd',
    'r8bBMqBn483hgwLsNJy4Ck3oVFTxdU7br2RKT7UGWcPbaUoMxv6V3qUtYdzwkeWhVgRa3AfLTDZ96xu93XM5YwwvHHqUnGVESBkhBPNuRnwmNyUema2bykezc2BaJe9EpNb',
    'ngmrqKGVX91c5aAWjzpEhfGdTdMkfSacDvZRR43Ptu4whfW2yzJvy7UwzK4dBfUhn5o2eLnZWyoaJwuaTn9eDSUN8WtaULRr6v8dW7qRqUowdeJKLbmNXszxRgbBYoTgYKw',
    'rThKGgPJkxRHUL9qCA97K6pW3RPDqprYjLHZiEb42bLYYPSxsbwd9pWFNdqKVZVhW7VtKA85gCs7SdwkENhTjhEvTe4NkYVEhBSpeuG5DdVBMm3mYf5gQvNKKiWhE29r5rV',
    '25L2qjS7difo6T1PW871rjnqjQenGCYTVmNZGAoJBqjdaBDNpbJyfo6x16kHjiwaB1eP4k7JzFhz7BCxE83xeYKDAU6rZDr3JeMsTrnJHTfcSCuuskbtL3xhW99qJjG53cQM',
    'qier5uHrps512yKXMiLXL319rT5dzwu7yeEfKi6ze5w6kCM2DMfdtW7TqcXdzPZhAB3tNAZ1Hv7Q2pARF6hnyusjdxVwN4zLoPQS3wsGMZopVXKXUqm3DySD9kzqQQFej4c',
    'n2DPucZgNznPCfhRfAS8aHQUktJYZ99wAUcYM5Qijs7XyENoF6w1bzHuHdX9duEcZTX1X7o7tX9UkFF35AE8JzdbGqN5zYNAnyGJXVogBzbDNKwS6GhaRRR9f95PUxRwtD1',
    '25HZa8omGsExfeeGBcege198RY5mx9fpGsuA3rDUamqCr96tBeprRbm1d1YL1Mr4HXi1YuFJ1ozH9CFRSauaEigtEatc7t321KffgxzFXRQaE8DD83P7NphwANV3jVhFdYa7',
    'qqoRXtqcJux5mNH5UaWp2WVdqg8xmAS9PfPUKLdEt24HKcj4SazPx59ctn23M1FskJBhxFBfnuwbrsDjRRJxEZynZLSaj6L4JUuGXMrtfFyxzL9mEUuWrjNk3egCTRkbz3Y',
    '25h5BvLgTAJ57DS4z4fuBJhj17k4iBfEQT6YMbzWPWuFfhUufVfU9ryohapjkA7rkb7xBtCfULZic2eJmCGssKdW2DCfBez26yXUy1qhRBnLQ4QCFadfM96tbUURoVYyYfWJ',
    'mTgXDqkyVacn7zCgoJfk7rKMVbvKhxfG1WD3jcXaXXdmUwiDouhYvGTGgVtYqW7MsvbKYtpFMKDRkJNJ5BWRvkP8TLHf2uz1XUuPU7cnz5nRE4uXaAhpCPPSjgAseybAsfU',
    'xc5LwKkUxzQ6Vhtd83Cuz5whAPfi8naDGvQPLhQPqmGGteZRGrfoH2QU3ZwGiy6xuviEfjpkdZNh69rJfg2L6PVgPBdaumX5AZT4N5Lyv9GAi1ZunJWQobKxXk2JGsWdZwU',
    'zseHtUg7CNtUThmcsnren1FJtK9inn2kTMg38jd74zrRzPP1Xm8XzXQE528bb9CSwABwnuMgVA5CjUJMYnNmzdMTMTkQHiWuAAmASeS27myBaEGEqg3DUXLJZdPzMxaS7Nq',
    'ufX5NcUWXUKkaLYrdcUf9yxmSjWngrS8Y5ErGmzf56DjHUqeonr3oM4cLMsuFKfm88WS1b8FPVoMBoETnuoTkHZ4whwhsSEuQzuPMQZy5UjLV5u33vbe8sFgceaYnn5XVsd',
    'mdXsA3Ee1YDt1aTcvUg7AKpzTKgJBoUDpvSRYmtZhM85dLBZN6VPYDd4BzFxLMo3RA2XKEc7t3nfipBcKQHbgpCqSZTZEZz8ohhMzqjDfvepuR9FPWCcJQfDwK8VZPimZ2J',
    '25A9dZXaWhLsPtgyfxNtdqpdrNkHzk7C3mJxGgq64NrRd5HhAQab59n6H5hLjkQgJvJWZbuZEm8GQ4UvtdRzXzB6nt8CMHWaNURLmhTzCnxuxCmJf5ws5WxiSUEEUHxaCYvb',
    'zTHaqm7jKyV4cSqrdeqCkeLci74v6ymXU8QRN48qxAoztYZ8hbLemskC9ycQqtEW2EdzALw3bwyEGmrG9J3DDeNKZoPoPCSLHL2Cymkf29zxvi8J23gB9MFwFSRQSEKRJf6',
    '23ws1motGfNRuZ4PJxN9DHnQxLTHMuKFfU97zgpFevcNXpbhesd7e5T2uxDc95tYkY2tgJC3EYfFjJXvRYFK2E2n8ogTjSW5NWurv1sarywLNGNkKqxzhyvSUsANqdRQBnzT',
    'mUUpjnXow2LHwm8a65cJsckTeQz55mRem6Vzo5VjZDbANnCoDKAFWESLiAPx6WUYcuosbSpYSoRm21amChNuLu3gqA2zo9VXdPNYNkfq8pxrsre7jNbLdDocqSfzQcywzaW',
    'q3e51AKaDByuyB1nM9fYpcgafrmZ52T3caoMkVD1iDcLQJaXUcSpNEiwvuTs6hc4EcMubf2wp3axfkGZgkgBG3FYZ4eaHxeB1gDbEWS6V2pPBrqitRXisURnNRnKk9T841F',
    '25J8LTkT3fj2a5qeRvxCRiXgakMqivtmB4iLzfJqrS3nvtpK1KEZcWrybMcRb7pgmcVepQTEoxTBQwHTvo9ZC7wrXyUVcpGrBSvJwxJxNYM68N8VwwWaBzjgnFTDEEy3hE3H',
    '22e4nDy3SHN1z6EQj7hQ9qwBASfoEXZ7PWgK1xYZGFsPXSNEBHEB4ntcLnDpYpePbjsuLFAUQC1YXTJdJN3bq9Gr6bwe24UiPXhZgxSHZPHspCeWTeoPiopw9zHkbhwBecjc',
    'pWf1wuUow5H95WxYtySqYMbzwY1xVS1FAj8WPXieuSBsYMgDJXNXzkHYhGLDW8v6J7qHNW5x5MSvyyvNLzUAJKsEr7udT4DDYZuUELERe2Q8jdR4a5t7rFpa7KQEJhf6bZb',
    'rSGm1CeKgLT7SeUWitc6XWMueHfcC1mg5ozjB2jWMANMuVUYze2b2k2mDYSoXqVL4ia5KUs3uyKWczDSMK4LGoBwWBewP22L2JeJMpbN9eZ39yG5AUfRKAvi78yGfXqeid4',
    '23Bgd58Xr999Xt7cgh671Lr77H3en5C8SjMfg41NJEnvL7hyZdo7YUPtVHM9fLoT9jCNRnJXmMMeeL3B9Q7JMCPL6ByjEDJUPzruabShyfSZpNAd16rnJ34i4wNx9Biic8QN',
    'mXKJ97xTtrSPzxWHBKPurUpehP1yPywcPVw554CCFhMtEL4Vh6jQTmFgqQD416xScqwEix5NCQwfQ9BAh1pkp3Fae6BTG5FxGyMEiP3VDzeUPuXjqaC9dp6H7JgkCK2o7x4',
    'zQgvJ6xQPCumYhTso8LCgmcxjATSuza5ACBHQs1t1XPBdxQkh56vHMJXrd89dJV5d6fXimP8HiS4Kb1jcj2YpLCQQsJLhiJDzR7PHPE5LLmDSPPqoT4XA1C4RL7vX4zdAAY',
    '215SPqmBgiheG8Eac5yBi6NiNb6MyN5yC9MKJKfUAtU5NmafmowELzZKXo3pbS1h2Unqeyw9BShTz4ZxNVt9ZG5TTLJAuMHrwLHtXicKpgrhTttkhLA14apZ4tDxNgQkCtj1',
    'qsT2E4s538wm9c2L53aXyNEzm5hNdyJ1zbD2jRs5hQZXVu55hD5nLVTNi8URnDcCaT14mNUdQTqQt7krWPjHeGxCjKyyQcdTpcHDzJjwMeAdHNRbUoWgoXzrFeEym48TRUM',
    'mdca2ea2KpRZaW6s6NkYAY29wbprGPGGo8MmB812HxUXcvb8dDDE8J4GjN9VH9FbB8GJdohgFKoK2oDFLyL5cCsDtPU1maWw1o7Xnzo7uHBPg8MmRfxyBCUVRji7SxM2zBD',
    'uvR72GsvbjCy2jCR6EKbfKpgUfHYQrphV6u915bQ3rHAEyPV5ows6QjtmoLS7NSvmJrBWgM7v92faivad82t3WDBB1ceUQmohNh6EBT2TiNALkwaMSzAzKziFEqUY67j9RU',
    'yjfKm8yE7SarRQuXYzt7RZ5EkFLZv67KfSiKarVhWsTdHiy3GGbmWF3KmYHvqVWaEGQoVQiP1A6vgrA7A3zt45Zc2zvht6q9REHkYLhFywmn7czjj897xXe7eTkj6itMx8X',
    'z96tDWGGF4cuTrQLZgLnuBos4VAMfUP3qYJ4A4mHWoEZWi5cC2P6hNgC5b9LiWLaWTYseda3teKrTvEjCsr3aPVDdLyhgrMshuJX8KPy4yZks5YZRt5JHNxM4fh7fX8fgTw',
    '25RHcLU8DPEnZm2iXy9qvQj5aDCcpE4B9KJT9VGZS24Qsv3vpbrN7b72Wj7YBH66aXNjm6i2URSQQnpdvQLFp6R7Jt85b8DJVHFrQHvhH35Z2xQXqtLk4Whgng6N4gqgq9h7',
    '248rpHWnGPT3puKGBB4CHdaHDnkFU8vaBNCUzV2bJ7JTyXA875PFPAUaFuUrMvmZd5PmBTPx5FhvBoPcddZhn7f97gmiPEpvs5zHEHbhfmWad176yKGwKkA5pvNDeXfEf9Lp',
    'suRcCj2X2THo8mFFYrjhS4bbo45RDeT59VJi1rWoq1ZEz9Xx9CyiqMsz9oWhNhr6g71aPWrBtwMJR6oxxhmvfNxy1Sd5Q4VgMWmmBAfwnUabaX6itEmVv9fbGigFyNtSGvR',
    '23aykwjPGYfhwqkSWksDs1TmU2zkBgMn339shztJ14oXkUmwMcS1E7EMUaCg7HKpdAP4e3NuNruEEeN36t88f6oinwUPNaJqkTtLnPjH4yt2QJsssgpD8BRyusoLADWG7i5h',
]

[[balance]]
address = '68UiBbsJ4PumJyVpS91VbffhKgq9p6QaLC8QCqzgLiKBX71mvCswmeViTHDsBJ3RMwsVcxBSkZ3HbjHAL9qCNxh'
seed = 0xdead_beef
notes = [1_000_000_000_000]

[[balance]]
address = '4LULsDGr3CkeZcVDSfM9UtNr1Xa9DF7HqCEnfnbsDH2HXkkoCfdQWKpEwKwPF6enrSVoTTfb2bGCB8v2VyHHFoUJ'
seed = 0xdead_beef
notes = [500_000_000_000_000_000]


[[stake]]
address = 'pFPEcfxidLvwmFKRQoifrSyWmmVY9UDEThoRFvGXddXRLZ8hB7xfWDYQYwHhTvZvXeL1p5Ygcnsuuxm1X8nHFJH6tEgK3cS76squcFVFSejaKJGMorYZdTup5uscNq6eDU2'
amount = 500_000_000_000_000

[[stake]]
address = 'rvXLHF8DBNwzZ63uSWPki3y7uNgGbdRCrKpouEP9N7awiGBDaP1uzyrtLBDtFbNgw8bPNjbyMsfAsNutZKnuX8JXzMiFvpW9vK4c2zmAmk3RygzwiFGCVJ9KSU7b4bgC1UT'
amount = 500_000_000_000_000

[[stake]]
address = 'rdHa4H5p1rVtQyqD5AjDHyr1EGg7yVU1wynqQ9VRqU8Wp7kMcePsSk2tURGzRLnzS36CaKEadpfRGwa3ucvFH5MEGYvF1LAqSQQT3zE1Fx7wQzYsrvDpJ44bBa6dKxN6mTC'
amount = 500_000_000_000_000

[[stake]]
address = '244Sywxj7PuMHpcPxemaXLcrY5rPgztra6H9Vz8cU1Ro5v23SxKTfVqr2yS7NXAXE1iq59ndn4aMZmYxuzu3Te3e9fokQKTUkYvFxYg2P2E8EEg1gWUbs3AFL2aNx62HQd7r'
amount = 500_000_000_000_000

[[stake]]
address = '24bfNr8MDUo5xJBecmeGzXDEraax4Cmbnhjyyt5GaL1Vbe6H48ZSYTpmjRDcFRDFzgzuePAPUNcdGMnBzBQBk4zAMgBCtPsY27tBJtKmB1st6qcmpzRR4Er5imxrzvMRnfWc'
amount = 500_000_000_000_000

[[stake]]
address = 'xEXp8qBarpXnVD9DJHUj8ywkWPggbPmgsmGFFtGAuXd2EXwEiXiXJ6r4WqdjvTvpE7Fx42TpwnkrpFwdc5BphPu7LCQ3FPU1DMQ1WKoDCxeQVircgHKrFpWsCZ8VLrGCdWm'
amount = 500_000_000_000_000

[[stake]]
address = 'shAky1Dnjxdhy1HsJRC17hgFw7YmT8PSdobce73k3ANmJWaDmycRyqruoxoxKoaVpudkCY4ENSgrkEoUgfG9xBa77jULgpDcWvYNLFQfWsA2bSFbooCJhZTHyGLyNQC73os'
amount = 500_000_000_000_000

[[stake]]
address = 'uDYKaU8SM5iriU88tWsR8Z7KbepmjiVubFLtetASuzEeBjwJZ5en4XuXjJTCZgHztK85gjS9que8njCebHGku9wnXzKbneYwx5xF1puiNF8XWRTcvDAta1ndsa4jAqGkWzm'
amount = 500_000_000_000_000

[[stake]]
address = 'zVnmVA7jfgAoBGnsMDrHGiwPx3sZhG42t6pysHjMj7rF6BKPGut87GZaDaXwmdjXsz53ULB2Mmur9aoSU1ZCGHYwQ57eN59FMwHqdBjULpNBfvFZN1qnzVpgz23y3UPPz6x'
amount = 500_000_000_000_000

[[stake]]
address = 'shB6W4UWipm3JQQgmbkC4Xy3CEvtyz4FL3QBpYUb5aRr4UspY4ezzq6XzoYENZgaf6p2j3xrtLuWNGcYhNU1jUdi9hS62bvCctoiqNNVdx1dXLJHyndHyT97Cww6Kmyr5r9'
amount = 500_000_000_000_000

[[stake]]
address = 'prV8r1A5oHHyMGuqvsyVP4eMfaqbYYtzKvfV6phwHMBNKaDnRCy4ntC81QGGS1dUDyqu6EuNamAEHZpR5cWWQkHvABrADkXs1fDbNqKtisEAnVjBj46iDJdQ7ck4vGs69Td'
amount = 500_000_000_000_000

[[stake]]
address = 'qHeUtHGi27ZRFHyBimKF6fHCy8B3mr2VShAkfk2ifkb8HAwD8Gr7Zrq96F9s5G4VWFUSbaUVcCBnExnumHeoQqfjRp52CRfzXDzkBevUG2CVtGqUvGGV1DxsDAEXHhCyXbX'
amount = 500_000_000_000_000

[[stake]]
address = 'sMnHcRLM2BTKDLrJUDcTQPAE7NhkNDS3v986rmV2eZJF5RRqtDJQya2RnLTN8vBodfHrqxVeVpFG2MEbta6YmNfokSn135rYhAvnmDwPL1nd3Uq3iwqih5hNBpiGK7HY9D1'
amount = 500_000_000_000_000

[[stake]]
address = 'oUgxBUWEPyFAekXW9T2UdJBcMF7xAuBfstrCX8ATXFk7MusqddFGoq2LN9euCbwVuXpSM5rGLKNUb6NVPFUVM5g4pA6CnXjNfNVBiy91NcH9eBVcdcG1eYUaKWQSYQ9t2um'
amount = 500_000_000_000_000

[[stake]]
address = '26brdzqNXEG1jTzCubJAPhks18bSSDY4n21ZW6VLYkCv6bBUdBAZZAbn1Coz1LPBYc4uEekBbzFnZvhL9untGCqRamhZS2cBV51fdZog3qkP3NbMEaqgNMcKEahAFV8t2Cke'
amount = 500_000_000_000_000

[[stake]]
address = '2681cRrpmrN17r1C1jNKNqAL6xc7mCTNu9qwhtjTVNHiaVioqowCcTcMqXcmYuqpG8c22bPqKWDRfRmzcfSnLLA9GG5jdgBhmoQxSAqaXMUL2Ee5LAGMB5RJycuUcDoHTCwY'
amount = 500_000_000_000_000

[[stake]]
address = 'nV71a9Hec6jeXVFkUN6JvgiLDTucp1R4g6GewvnL7nYLbRrcxuPtFHt2PNjApDaLXLKTBEEwMdefjnQgKtBFaJAtA1jxkF9K2EKW1nBea26cHcvb326rbXNgYA4pNWv4roh'
amount = 500_000_000_000_000

[[stake]]
address = '26LsKrN6Rk4UPALU6msRjkdu5tdSsoNtudcMSvz8Xa2jmp6gDCv964yf7rq4SC4bHDCuoT28KBS8989WfTjBuxTdYqQhCswDL1MiDhXBvraiWPX9Hjhvi1X4pbs757sHYXGb'
amount = 500_000_000_000_000

[[stake]]
address = 'uSXgfWF1uhmxjmLaQPXhVY2NJt1UNUKf5xTGK5eCGF1kFtnhG2DwhYJGX4kowZScrJV37vEFDMPEzG4q2hsjBoSMbnMjz7qUWevKA5UP3MBZS45k6vcjHEF5GB5CeuafQwA'
amount = 500_000_000_000_000

[[stake]]
address = 'nvdsjA8biVgXQc7fFYxJwZAY7AM1wc8YqYNQ5fFe8NYQZnVHSRny6yQadz5MNXzsCYhcFHDAGqrgVRDKoPNN41Z2bwy57SZwCXSBrx3SnjVbefrRXzXAEuHMfUEBBtq8gzH'
amount = 500_000_000_000_000

[[stake]]
address = 'm6dy2gz3jC3ifLpZmdTaZbgcptWxRrfnQEZ8hG8ewhopKXTcCTnTqs4UeucXFkcSuFMfTqMzT1Go6KfNkuFvJPvsrvp5vKxEccuJNUgMi1uSCne1ti5kgYeNHtW82FWtnpf'
amount = 500_000_000_000_000

[[stake]]
address = '26DsWXiCrNxkmCZ1zfCh3XTE2cXqf4NEPGGRMU39vZhNYF6hExrRrzN4nETVYduLuiRAHmtonkP6TvtVnhf9v5YcksgUfhHY78dNgCTSZs9WgHjN4NP2QRiybAaH3xUGeatm'
amount = 500_000_000_000_000

[[stake]]
address = '23fAnih3A9TtZLmwBggRgjGHsEB9qyVTq25C1LahSVH2LigFdjLxveccFgnfQPxWUmMFLJDh8Ptd4NivosEK6pDZoAb48EirBaKqDEExh75iXDsr6k8hjFxV2hJhfGtYLFGr'
amount = 500_000_000_000_000

[[stake]]
address = 'yDiwuTDWV9WPeihhaToqHYijiwM5n84deh8Nn779WyNr9kGFcRLnHHkDTcVpzLaNSEa7b3DQQky6i72hvsrKJ2uFSsJQD37pokQKVokV4Q2q1p1aRPNRdSujfmcdMP3MBVS'
amount = 500_000_000_000_000

[[stake]]
address = 'txesrFKYx2Ea7foBoBUNDj1rn1MjG8KREfZYNEb6UGg1k3KSBQdXr52Ayfemz1cEJ64AosipuGH5khnSXq87EcKP6uD2JrGb1NKdAgBELYkocXpbcmANd4VupWnVCPoecr1'
amount = 500_000_000_000_000

[[stake]]
address = '24Qzcp49pQt8Rb1bWf65Yq76QysTfyQKUZh7C219345iD6eYfHKptxxAKrqGYLFXKUci3NR5FbLhFjmLnL4jf249hwZK19gY2nqKESbSyfkMVMQHpS5dVVcN2my1KWR3jha4'
amount = 500_000_000_000_000

[[stake]]
address = '26TVUnyxdYwX3Sipc2RLAwGnE6gLHW86sudf2HU3xP8S7NbAoiJDUE2XTn1FaEKV32FvZpCf9SjsgkYatddn6BsoBhMTmXyd1TMpzgFyJ8rGNXNN2R9LBuHfCXoXXj3MtNJr'
amount = 500_000_000_000_000

[[stake]]
address = 'o6Ckan2efbGTbJRSgzM9vwK5z4fTY5AFr3WqWTRNVL8dsXxEBkEqa4wsHs6g3ARWZovFVEkV3r1HJZbhLWK2vC8xBarMRKifta7xZNeprb5xUFpjeS3ekF9VBsnKPbwTtP1'
amount = 500_000_000_000_000

[[stake]]
address = '23hcRjNqzKUhcHevbiP24NThLLbCjMXDFdwFXqgLjmx5cheXE6drSuSiuvvaSc7rbnbR2Yb1NY1x3276WVp47nFUM2ygmmERC4cxuF51aMqu75PVanouxfgmaHtFHjcHoHjj'
amount = 500_000_000_000_000

[[stake]]
address = '21SQ3HyThUvJUAtn3cfYUAisdw9h25DCp5hT2vzeiiQrvjGpmjsZKmbMMQTFSfU3EsEYtLqncXhVRkxnapwYrjYmR1tVdx3xE3nz2UkxSD1L34E1aTCoGqqZek9TfmSTQ5Sn'
amount = 500_000_000_000_000
