[acl.stake]
owners = [
    '22uowXa4bAwa9uehMFoSZjGCDTUSLGhFjCWxrEGHng8kWsEJSQBZxcCa8PeGMdTXWt9XyYNEx4S85XrGwfE8G1iG5j1ptEU4sSu1Hq3QKHsnBEZwTDLNBQeesSfmUadSjfRh'
]
allowlist = [
    'rm6jwcM9xQChnVeHYw6W8HP7kW3E8nejgs4XhmKoYspQnrZL5dDcQjVR5e2UmbyNNF4DJDRdZGdYLgJfZ3qQXuhSCL6UTDkcQ2QEf6RW3aCtfqQMKCFMNaBsfNrZuzrP23Z',
    'uazLgN2HtLqaDZCxAtJtkkurQTXyZWXjQYJ3HdSVbpBjGRzMvKaqvpx3MRw8HTv7bTwyviLosEJAa56G66cdNjL4CJdqTUyFHdufzWWfLz9E7eF97tdc6jZsVTiGXGNGf2E',
    '23RRcwBV2BsBVvmNPUh16xCYfLZj7qkxjCFg8dS5hkJcRrnVbFr5sHHGvTYbcvyDaZ19D6jqn21miC52y9rjycYrG1EBtc1wYwZLhZLHk63L52aaYYoyJtgM6hbuzmPXVvaQ',
    'xxRf7HtmFrcNqF8QpEpXmNqEePC7ftcrAGyavJQUv5mQrZKmS1GBazS1fbrftFbj5t6A19F4FComuyLcS9dVkgu8bE7vzA4QTfEUWWjLU9As9FaazE8ewVEBkAe4f8SeGny',
    'uZvKUYkVz7SJkicS4gQXGAjj8rziVkcV7ZXqGJAKNSW7iFFfTYCdo3k9Hw4A5dPfUxvBDtBPiSDjmehZGEQwDSYkdSf39WDEbavq9XHyzLY1S72EXCbEoB38avxaY7eXp6i',
    '26urMnP7s57oyDYChtPoxVH8UbW2cRNeCXPduv3NCQ3E5syWK2fpPVS31fvDbMVR5b71WWktDCJGpeCFEAK14TKcn7YJxUoYASmQsfpvd3WcmtPoG6muA7LXKL4zZYstCZEV',
    '24E3rco1M3m8CJrCn5dutn712qtYFTXoNdW7hzTSLD6VC2egf4Aii1cduqLWvHW6dmpbMHrxUtypxJEaQXGWv9EMZShL7m2vMr7CRuzjfdmrPGRyQMYYLsZAqgEyELtn1ure',
    '272i7KrUXdG66sUyAxbSKPKxxm624EdEhNBr3HKm7SDgLwB4gD2BobuS7RDDeU1Z4mCFXbxu5uJhoheAYo7Yc7ETDXUgXZSVBakrBrWUBwau1BVKWMykYDuevw5V2W3D5AFM',
    '213uCMVTh44twwWxV1q2X7yKWDG4VXGrDGo2Sb8GzNWVQTaext61Po21pFcPpJPFuYqkqqTxyTjeZJkwL5GkwKDWe78HTyYCh6w5RYtp2bJeikqGXkabbc34xYYLc3y7F5BA',
    '21323yLXTiWyRy1nekrjmzaVfJNcpDYWaNWww5yC3ATqR4xQ8hcE5aRbHLzDcBfsGBmd9VhuLsKMLydQpv5gsprn2LrZNBus3x2vDbAWVRMaazehrNvP8C92uSspPjvDdxtd',
    'r3JZKGbrcfF4rnFhq8AM5aXWW994yKAFK5R9JRoGV9UYzSPumePHMRGEmjqepMjVhqP2fk9Ax4TrVvSM2JeGhSoMVbwunjHtgAiZnPZdAjevJQ9e7XwdfwQBaFeDvAQ62ZG',
    'pedJJvzh9GuUQXE39JUZPnQkUahXoPeuVDUK1MAqN5WTsHViukdKd4QinGNtqY7VQyRYQKNYDsY7pqUV89bvAGyeHjF1XC6rKhUhsYuWBHqhizcxpjc5cpLfH1vb62ZGXZs',
    'mZAnxKrBuBm8Bgfr6PobgwHFNsb2VcibPqDz9GxjABZB9J7wJYidkCBdnDwoPZXj7Gjut8a978ADdVooutRH6XH2zvtx6S8EH3Ax8WFFCjHEkxK1wisKW5bb5tWYgkQA6jK',
    'ujL83YgGj9MEhydCQL6vfGDvUWfNFV69vzQbdYHivXxPJi2kBTWmGF8mKDxwKsBoASX7UpFg4vRkzio76GpUc9sFfqC3obADv5o2AGyaHVsmqdt1iUDJPeRSg339qgZevDA',
    '23YLXnqMDSS7Dts6MtsaMazUChUaZdCJczJT7jSKweAQ5L9KTYqCUGPWMPMBGxSCgGWPkmEvuezJ5RJiBxABGCQmbopxti7voJySHZU9yy6wBqrvnw9pTnFLbSksYgU9DzP8',
    'rRjBVYjGcQ4r5ea2KT9MzhHbGqPwyJZJM2C5N3rzdt7VWDE6qqpnXtqFgB4fXCmBsfS3Zsf1SxCVT9rz1VGWKxCFXVVYRZpXJ9KzX4oP34vS1ZDxQyzwZruhRknUx8fowpP',
    'ncx72nK92RJT1QAV71DaPwNtV7LAZDiWNu7gCennDZkfXyjh6bRiB3az2CL9St8aFB3tLatZ22n2FvoVfVtvLrtKLtmScaupQmPnkxeLj8UEpRX89oP9Rm1h4msVzFyQ4n1',
    '26URNquMJ4ZxbBz9C75zC9ExUHHH9NFSc1XVi8FGwLwtTfXw7f9qwnUknTKR53YCfCPF5hTSNuM1iX8Q3bgMVmEotBf9CK3zHNa2HPWa1XRmkbkoN4A4vyUEaWDQLM7ionEP',
    'mcEgJhr4fPZBfYCejkVCYxpLQc6nYN5wktSWdrwbqrWpexMzKF46zQSCgN2nGBJV72ZR84fYgoj6Hrhci1gpmzEqNytNxESjg5e5EfgG9Rt7ujuf47viVcznsGgSCKz3dhk',
    'npbMNQM1xKYsxzrBx5bXDmCC3DKPDyw6WKYnHQ1C8tDJcDLtkNQGSU7GEoM1NUAoap5pJHXzxo3MAt8VDXxKAYg5qSPZjbSFwYJofX16HQooQbFBDF5Ubx6jPso5uVAt5Wq',
    '24PrGq2BzPE7cq6v8gpmemwbxFpkAw6Ui1DLxsjN9KUbQS48dZsMnkDsEqnYVhFX4EMXULph6QBoT5smcuDAu8mfWD3u2sSD3vYnqoynVDXrxexxs9EivvSBQwWjWdPbu2qU',
    '23KjUiz6qUEUquZdJN3C8owXWYZSaRfuB6nM312QmvjQgGYVfijCqiyFY49PneqpvBayxYpz1CLFHjktqZwdtTStJHZXSmMooKdyLyZA8fy3ffGqp7JYTkZABiiY8NeozroF',
    'yobLCBgyyZhk5Gb3t6StQHSPWXb8Cf3U5ueShEgEtU8zCVSDTq9ZHqvjY6Mu1WA9N4LUjYWrm95Mb4C7VRUwEHEhXfpyqVdbhvsLiRjuiAbun2AUe4FRwWZk1DR3QdYKc9Q',
    '226ayJKXKQfjESvdThBTmC2aMRDb9GABQ8pcGvsVKpJWR7mojRSeyARRBMZef14yTZUGuSRphFinhSU8qbngjvdwNeZoBaWfWVB633xain1YHDZAYJcFC8MiEzELZnTLEaCT',
    'qEw65a4i3J7bYeFMdV5agXzKaw44v3eWyXjoer3nZqou6uF8ve7fFCFpVLhgdooE4LDjT48xnihtYKypzbKzDMWzPXb5Vrrjspo37WSfUSYD3VhtL61eDNUp7vBqaYP3Q25',
    'uBF12rNZUZaPXm8BjQ5qv8em27ZHqEnXxmTiNk9FfUnZEuq6kgWPeG5LrbSmUcheLydPjjAjsYiBNfKPUYx66VW2Xn5K1Qc3TfxN2bVSn5yD3XH1jma51xxAU1YBJqu7Z46',
    'xt9UptXhcm5R82MqskfyDQpoYAeuYCPoqpLxnWtXyE8G8nec6W2oPPFACE13z83wg5ghPbLsmdB6r9mHM3oMEDvfT3yj5DAsAb9JcMuioi9FjL2dR6r4zHGjCfRjhUJ61iF',
    '22Rej6Fhg1AsBUaLu5fyBixV7gre4WKZUeAj7WQSqQMDw2dJvzYHwLBpkbscaenXDfhVpPEuQuJmTct7ECHeXsvskAaNrf3ccda97VpbwZSrC8eh2JLjjvEidvJaqoVB32W3',
    '258CGbVo7MjbY7YWuZQmUgmouv5AL8oKLLfk5mg5jkS2Y85cmEvHUGH4XeVgrbG9BYn36PfNeAngDcNH7TbvAevCe3jpimYb7M4NHp6sbwcUGwZ8iuMF5nwLnAGLJoWm6riJ',
    '24QhoKt8QVVeHdGEh2uXt8XSy3tPV3ZXMwvv8C5kVsjLoqEiwiYZSEFR6Lu8JWnyHqcgeFNCZxHM1U7cTb1dY4vUCv8PoTwpmoBJ9zZ6E7SZjduf5TjBPidpCvJh4dTfn4bV',
    'xepMipVxnqqou5Sy9AaD7hGdFppb8mh3zY5bBU5paox1Taq7yQAD69DufwJdwyLPvjwkFV7ZFXJxAXwWg4b6QAzvrUqzGDCzQEpPp1R8CVvWELRcEB5ZDuL8gyrM21abVTQ',
    'n1ToWy3iTxhmvMCxpQNdkPLGKYA6byaQeByouA4gtj7Wm1eUAoZYFYZa7GC2p9eopzr1a4bpF8HrsgLoUWdmX6gxssuauzrCpRifiFWB4c4XKA2KPWer2MuV1EWrpciSDGH',
    'x9cBESqk9PtvQ9SXaFzNk4zQMzRep1ZygxZnxsYPJ9CG1HECMNHHr4gmzAvbYAndFTDzFe3rsiHfeW2HNWrkbyXCKiaBjoE2PBeQdKhe5BdEssfKrewzw3VHiVm2ub6Cjjc',
    'qFhxRAgh1gtLWUdYeaKixZgmyjyhetaxVCqAKq9suStsxCpeoPg8Ep45M3VrjzpbtVGjHd2ngDLHabEgriVU2dyik2mxoBZhq2CtiqHUag6w28e436752Uid2F8Pm6JEGhW',
    '24zbEsBkKuweRN6bsPwpxDyuf9n6uWCjkJ43oyFnCDmHnsEr7zZnrVC1zCxghyuojMYpibe6VxwqxrWGpnLgos5ZFHemVxdoPk9ZVvYjVAzYfF3GCW9dPJcCS8vtg38Cva1T',
    '21ZeUMTrqaGH615S51AehXMv5g896JCFxk9byBGF5bgoUuAMuRr5dB2DURdh1sx4sDfC4CYpua73CBaGZTL1H5ipzmnSU6dJuKQXZNAZd6gQuHVaHNaNGi1R9dNzxHZL6mee',
    '21s1vG6ptyhf4r9Bdu5px1Mv7mGEgvukRS5oip8yNukTv9LVaY5hXwdRgHbhWBD1nYg86GBqBEMjXrS2nsC8cLASbmPDia2cUeCYaZDDFNXvakfqgKJZgAGEFzndzeP55Mmo',
    'zf36XFJLKRyGCKyqhGiiaF9dopAPgWwMv6Qps1TJqRwVMKtNCYi8X45PwgScKHxUP1iqruK9YSUUB278i6332rTDXzSf8vMTZC8MZN7KDcaZ345zXJMfETUb21iB1ckZBtE',
    '24fucWY9gMyuJyAjiFqdsjgrUbLf6bSMwnhxSujLidp1uKZrBJHd6gGadPuND5CVBeedvNWnSW3RWk79ytgePdyKhY2MQUr2Fw8mjE6XXADFpYAzQShgSeYavtKerongnqtS',
    'yTyMPcaVSyHeXAohbiWw25eyKEws6BFayvrkZMgybCKLogYEHpndQJGiSXxbczLUAuCtf332uTKcHHkgrJY6KwUavCgdo2Q625B5Bs9NDiSzKo2oSyFCac65ETJAux9TVwo',
    '24CFAzeciymKu7qEs3hHwfeq2ayCvMCzakauRSTgSnM9oofvb9uwfqE51dq9FnUTiCKjW9nNUgznWGAuQbuNSsAL6tgemDQ6o1ja3d4BH3HhpE6bE8Cfv7zBKy7WfU38CBcv',
    'yEdGBvotQLUoo5U1vTjfPxZD8ETdMCEWosYPHMYUz4kLpqBTpYNeqTkmnfcZSQnPYmRFbPCrAzHUGgkTgBSK4BMyrUo4Qj6kr6hEvVvf7xWCi8x8XkvHeEKG6HyYkvyfL88',
    'teFKohDxZee9THv88hRzfXH3EYYEqKbV7E7nDUMQiBDt9EcyFdBfFhr5xKumtntAK6ugUj5hnDfsC57SS2XR5XKB47w7xjYw1F7xPoVQWWBKBpezi2rPNaCBWxVZQxDUCAb',
    '21ooeEWW78EiU3JAyfpGuafkEuhAq3GFTNfYkDt5eifqsiSEpyPYeFj5YYMK8aT9AyJis7c6euDbBPZM1Jkmwd6TuRbzXmXvfxq2EvnP46QTxyo5wMN33xNiAbF8WHQg79uD',
    'u6uUEanV9aiSyy3sTYmepy3s62SE26JGe5LZ1PDz2JbnwACZVjRt5mK9fswxgwT6CGMtCLTj1dRAMnvpSSyfFUbYkySa5yZnTccaWanZPDNfCUztdBAMrDfT4Ythwe3dXis',
    'uiPUtjanNoNsD3Y9geznp9JubHKpDtVeBivADHTULkmpDWFmdmuVsSqfVFfKP2CE9iWUHCqiHrr2veDceVwkmR1hBH6iXJzYXGvbp469hJZtGRCge9L4LhhU84UEkYJkgG7',
    'pffHdA4UAaDToPYWqk2JTwVUhMyKDN4AxLtQvzbP5Rn27LUoxz6WWVFSDddGFue5HifCjxUgBMkvVL5F4jgdfPx4A4atiBDb49bv1cEjrY3VrXjgDta4zVLLN8HnPopkxhF',
    'zdiskR1RfUWHFwtZWBokkpWA5DGRziiT5GL8FAxUQ3qg83iUsBnadrKHF2mBu59xUXBm67TomENmR851khsK4ZMH6QH25SbfE981ZbZ7CZ8rTD91EZf2qfpS35vgowpBFht',
    '234cMbeHuXyosBtA6UDqGh2PsPF8GM11UKA5zA8j7uUNyNH3Ec4r57PdyBr6KMMbQVGbndjVK8FyQZe8hPQC57R2TbbmcmktxD2z2yguU9hd4oax8PijhFxC8Kx4VgjjM8nB',
    'o4PYYLUks1ynz9oFKmU4huKmiBF9uvPYTYjJ5M63KPSmNPZhmZhowxGNGhv9ckGNyB2MYEAePoJo8EgbDhBhwTvYkf5QbyiN1Js9ZHgLiibs936RQHW8esZCzjhnY6Rg3PU',
    '23ZuJ2r7EXc4gMz4Ba7s9fuzDKwWgKCxDkLubWYNHkSJ7LwS1KrZdX4YvKyCz6EdYpc2NwMd3iKyaGBDMaFWkHFcQafuAyxtt7dBQ3UoSsd7MNuPAWoGkeq5any8DXPJXu6u',
    'pLs9QjsPCMMWSA6tZLgWQqLaYGUETuU6hqPLDBPMFKxi6f9iRRZXmVVwC73qS1kDdNHD5UhK6s5uC99mW8nZCtF2MJ6YG6ezomkksuFZYdxDTnVbCzCp6zBt4ZsxdixFvAU',
    'mg4yF8a44PBhXBu31Zf1FDh8TriW9rHeLnMb2CspwtJcLM84sahgAfKM8AH2tuB68fmBgDVbKq1pJ5mBjjZqvRBr58G8rGrjtjtDhXLPxxThf2PEiv96bix3iJWLmx1GFUa',
    'qyHdt4iJVRqYzRD41HwHSHWQke3W9bMLjSCacPFkuMKyhLSJ9AxMERsesExiD5i2uuhWhFsHC6jdw8NauvCzRvP4Dx7gysgZRkZr9qdKZ6NXZP2iwLVUZJEF41rF2vDvn5h',
    'xcS4ByAFgWApEVFViNYmHKKoXB4v3Ev8abgYfpLsHr4niMTijNLXitHFfFGgNt3M2EoRhBfQJQRUidBvtVGwqu3vHLPNh2dTkiuRm5KwqgWrAaWQZanT5VbcNk2KUYZWVBu',
    '22JUYZda12A2KgGSxb4gXcsnN85whHNcsC3QrkVWv2JKG3E6b5AdZjQQbivAUYZvydTdzHbGAmhDvMYdGyTcwni4YqCrJTbiu46pRYHntRprRjKjaXMGCBjH8FCZRKBBenX3',
    '26bqBwLZvcskvweTnsCprEm82KSw4V9RvM4qv19Sz1ZuVmEa2nVqHgCPcLJbjdP9breWwMtAMJjK7Braq7fuuVtatKaxAxad3frS5z5ZcaMdirppDj2CMzwSkLYG4dns2G7W',
    '25HKUhMeYhyAg7nnHYtNY6DY7H6hA2wgALqJjfR8t8yBswgShXVucNqM3nR3K8nKTjQPKX5jc68aFRjZ54VsnzC4JtXoCDVmNrCDrw5kS9QQzPt1qSG6qXK4cgCpbGdZZjYg',
    '26WvbqFbQpmRMd8Btna4B9taa3ZL2iTcaAhoZQ6EZ2qyGFiwbxvWkQhcN6f8WKPGyaEjtLVtuWkjcgsd6CWc9YBb6DnbTikjbypok7NXeLM69QMjkaoM61XWt37cj9yJw13z',
    'nxypoY8H7TkmUeFCUAggd8oxrdDh1WbhyDhsoT2Zxy3WFXuc1awewM9Hzdgdf8zzdxYvHTpCFJe4WdKUMEz4cwtHCdrMaebgqM6Un3JMaicVRkQyA7AdS56AfQA7eXtkxeL',
    'u5JJhGC4hHoV4C15AaAjBXQ8CQYtWUKdxwc9wPj5Se9pa8rAadnNpcXS9cUUQzVNwpzrfLFcHLSspvk4fya9sJ7vfhiS3nnEAHjsi5ysXfp5VGrCSpqJawZH5aexpNCZ3wQ',
    'sSAqSiNKa1Mc9aVT5ygNNW4LBtN28bGAzEe1MSChi19PPEN79Kd9sSXwPtUP2hw5vgX9zehruZhWp2w1FNf5wkMiRJQX88RKCv3bdZt2hfUg9zCb8hCUG25wrHtfLihe8tS',
    '21sjj1c1VBmxxF8DU6cUanfPxXtF79SNYMe9RVZiVYguJZ9vtPJNA33gAgr1WQTjZjwyQiUW2Si8EGUTiBHeLgj7pfTiMzRo3VLHJdvkr9xenkch6JqxP9YXRxQpsm8f98qq',
    'z74c5zwqTE4wRrraJmpNZrfw2c2BPytcdCP28vnR6W8arEcVUkPJPUeKWaohebwFBo3ghMcoKXB3T3sCoomSUbPDRZjPfRz8XdKgn4uUAvq54J58k5FWugkqWf14RsR3X91',
    'nD1KokhRwHhpzzU9Az7zhyC7jn4uBvcUfJoCkqm9MDnHbT5cTnhz2uy2ZuFRrJBq4xh1zaqp1sRHVAyWUG7LjkyBgwNCgScunegBp76kw2tttzUTmwpaC121PASrN2CTMyZ',
    's1CFHvY4Wr6qTgTBWWUMGqf88wHwxAFiFpYDVUnJW3vrbUoycxTuPVM3XXTrAMY1cFxNvtYiJ9rQaXXbXWYEAZmphXVfhF8Laj9CR1gN6C7hMyBp81fxTgxuShoh3ZRoPKb',
    '23szMpgcJrJBcWZnwpnAPdaUWd3cAtrwiw2qEaQ6aQMQzr2ey7iH43dnU2dkQeJzxzs9rcaUcnQJ4K3DsYEShGp5aVtEPhHTAPFyLogkiyWSpQgxZSvy1cJGdALXJ9DpWabw',
    'xYeb2UudeMmULdyttRAei88ZJwxac4umStAgCuGx7UK3ua9z9zsnknoNGZjeu6rDNXfF4pvTZNusKdssJS7ZWZppygtPab7SNoHMzQrNHZP9AoZcFwAR7yvfZHKYKPgUwtB',
    '25XiJBUxMSvoALURzHKpDQEvuoH4Us3YLTJAJDasFuEThn1mRSg5BgwDJDSowSVtbXUYn18GY75S3A3rfxTn6LrxnfPSWAWpgrFJQUWjvG8Fj9EvWBoTgV142SFG72cdWwMZ',
    '21uR1wScM1n5XjqBA8QYxaEZuoaUyw46oAfE99nMNzUQNCr6DRsHzVH1uuK57j2fJ6SpTohjm8Y5KzhpP4vzC7vBbcX84eDuNNqKKKePmyaMowMbEenswnMjrZNVqvrSvShS',
    'ucGAKkwLzsteDQzJbqNuYPc3C8esgF4o2taVrDNTPXuyMQCaJkzn7EtFzRonUKhyUiiK3oV1Mmq7uhNrVDGZdJjEZshRt8H7CAFgJNohvFKAXad93xfYrFgerBYkpxCiwdg',
    't8QjLzB474ySv8bJYfo742TF13ztivimL4PxJ8qwMhTjCpDKHens3Xxk114JxWhHuj5krnhCrcH8mAQeqvofPasUo5XABP7nymWaXSa4VsmMi846LZzKHUm9snjwrGaAgPU',
    '23ArvurtqKMcvgf1qFjTDWSmqrdLABUJbgcDge3LFEnskDVGbKCLB4g5oTLGKBpbsL96UkkyFRppMqH7bBtVyHhbCPfKQmZoG3K9cs2ajQr3h6ah6ep55hhv2dmvMeUHeRkK',
    '23q4jYeJwmELqyEfLjHAn2hyE3wE9crYUhm8xRZjeCkoeBipyfkGagm8hVBVE8qEZ4XSNJFp1TCSKEF13TGDN4W5UnatH9epcw8AUN1Pd4eyvL6a1jZ2UaEoSMKm7TqLP4Gy',
    '21HQNQ3TstFvUtC7h4GBnjDPoQDUsmXryJYwSGGfr6qNXk7itctg2gtgHsJDcbZYqepDNhYyKesTfwNuVnSVqhH3bUbpaPB6skcvm7b2nwiyhfRbcHBE4PLupusEhsroiLqA',
    'tjGoDtu31qZ6ivbXx4iLYgPYh945Jpn3563XPNBknfR9GPuK5tuehQ6RA1FkWHSWw9XuwZ7TatjcDLLJuMVLmAGFygYCabhg4CBNmcof86Jy7JADrojTWfp7GhVJgW93V5A',
    '21yTSRgCYV9jZzcULcxGiryPtyvBwXmU8VF9zmqFMEW5C6GZGbJhh2S7Eqcb9y5hF8P6DCty1WGFchE4pD6GNsTnoz5yQXvtHE1EhYTUMtEXfQHwcSMr7jP1WGGnL9wGqZaL',
    'nzyvZn2Xxm5SH3UupQL2Kaw9nr3jMoJmikXyMiduXdQcSAhdL5YGZa4e1AsquZJBzSZA6mjG9Lqp1h2Gjb9kfdweCcjTNrWS4BNLHcN1BP9VkGv4VTrY2umDbtL2vKKTXEZ',
    'nSevwT56GZ7sjqYAZsRRFW7Dctdq52MvzgKeu1Lt5cNpnUyCz3xRezAKbxbRDniqYWfvKuNZHoJoFrgWvHBJevgheFXFo81MdNmFDBtdsK6UnWM8neodjHzc6fTCSvJyFeD',
    '224g6k2HmGGwAdWuX8Z3B49t5bDATjH77yR6k82Pd6tuPSqsXbV2EWQhAfPfxA1fp9y1mYryfNReQnZWjrH6UmcUXEAwpuV4naiQNNFtaHqs5MgsTB3NT2hGMfw5zaXz4RHF',
    'yNFKFeq2ksoS9FsoEw6KDxLn4rTZ7if22vD7R8YrxbnkoU7v9GSmijHP3XE6THAJZZyd7x4qwLQa2Gi1ojsNqMeDNVQJjLjfUHGmieQ4c6Raw5f1WcK6Xz2RG7VhZ2WvLBx',
    '25HhyGqoGknSLQBEPDsHbRFBGVUB2erofAfYRkfRovPMTe38qkbyTJgfcGGXwH8xGJcoYrCoicJn2usBNeSDHRUiR3cKCLxkEQjX1HT6U5DwKzohZQwrDHAQ8r6v5TEAe5xv',
    '26SxJHUPDyG2ostRNkghZq2qLNAuH1med9G6vAfbUzUotMPJvVTUzPojqRMoZyBDm7CEy8xUtm1qkY4hx8QXBCVFNoi8P5LsEyrHeqgmw9MAhTz1sG5MBBadfKERb7rx3jwM',
    'uWd7gn2Mk1ZcdzKaZ91Z8De4UBPVSmPZ271K3uXjsZK5ZZQobwspNw2wcCWXMBMbPXZWRX3B5t4jCMaL4PBpGqgXqxeerhvEN5GRc6rNMe5bBN5BvBBAavMPUpp461Gxp4n',
    'n2Wjjo1nLAbWiAmEJwsQjwVypnhk3MyssWDXLKtU6a5EyEJaN3etJEaBgWe35RGnrLUjCd53jw2qtuLAtge6Gov9NcNB4DEgTWbaUcz7EoyNLSQLk45gnZg2dEaGAxp1w5F',
    '22GNXdXKRebsro2FiZsSvFuxCTBzDmvuMQzEBKN81ZK2RJg1wkFaFtaqSF4ooPqDGd5n7Phq4CSwt3YcBPKFKoCNiGNCrApw861hPpdQ8NcNq3MBJ6KTXMqTMSjoBNeMsgZj',
    'sQf2dezLcqZus4mh5KfB5keeF2FQeoXyA2ABzgDNr2B2dS1dq87ueUFNHyKy3DcM7qw748T68PSkpAXkmbbzCoMT7FdKuMnM1Ht729GjgtBqUdgPVjNZPuE9MqSxwtrjnpw',
    'nhkM2nfamRmrgoGa8JYnfaL6tavSY7qRrduY1dG1NiQtLyqALHz9XtAqbhuuR57q9oTVgqb5TdvBrKwm5gYH2zLjSwrq7C4gYwS7bDRqhM4ZogawoJmteKSAMPWqT6EK3rn',
    'm8AHSke1BAZPVBrkLjGEQXhfhpzD7yfd95bfY96LqiJdyuCVc16qpHYe3JX7Uq8FzwvsCKvkvMeXyAKCkVNsPvy7uExY9XNTF8hQbXDf71AEEu94Fc4EPTmFBLYG6TQAMEo',
    '212Eszgyh7GqMTwspNw4jhT4eFdhM281jLXV6CKyF7Yyh8DAv45XL9iszYnVArAYQdBP72jZkvMZE1gmnY1PJgo4S2uvx5ann9iHUyTfHxU9MBti2M9ymytqQbBc3vpDEd81',
    '2232sf7xouh6x9geCQCXjGBf57ezX274ZS5R2MY68UXvu6BQP6aUbVNcWQgWzJo47q86AonZiJePKUwbGzp5VDudMKpmxS333Vn3N6GHtJA5w3xG5wiY7XfXix1XwXS53ECm',
    '22z7SEfWy7VEZqi3Ru6MDzBtHmZWnizPW57t2CHGESLGeuamJ1v4prqPHHrjUkQNW4wJ8mA4nNgRHg1MJdMpmbrar4sMisr5b6tKCCUPvu7hFkKPEP2cdXZkdEUXivx6fjAh',
    '23wQuNYp2dL9BcnFNnizSBnxjhHerR6WjYFNLS6qmM3KNvf1Gia27u3Vkjg88jCwvwwTSHWpEDCX9NojejCKZ25HvZLaDeLrfkL2wCXFXz5GT44QGFyQqM9uN2taNjPVBTkN',
    '24ED5zGePkU2Tfpp3X1NxSFhhgNCYBakorBJCXEhwVeWwB341XY9Xk2cJ5uhQ8TAHXGyJAE4EZakhWFkPy1vRr7moR8A9q47P5kkTzo7pWqggog5Lpjvkko2FJwKNJJRG9mc',
    'uqMkRzvvPL3V3uG2AsZ4M31G4d2tkCRVFEcaeCt2AQpKcFKb9x9Bxa7xTYQsErRp4TsJP5DWyWsPLimTMvGqXXGJEh3aeCYemzD1rwNBQ3fbfD6YHt8T9cLH7MjeAQt9RQv',
    'qFDZZfE9SiADC9s4wAy9mdFHHf4FhG9qZwDd7zx4SAu1s7kjoxgCbMDe6kN2J3QUFE2PPvBJttRhhz8nsWBKL4kRxWwEda2TY7kYKkkBF8NCQiquvB39cqb9Qwi2QHXHcWD',
    'xSZi1pVKSytq9kyGNVkx5hPiXefz8E5Gt7bVUUGosa4Fpe3KusNUp7aVKQcan45kJQL53KKWV64dUkveA83EpRz5ppgNLrNsHwsxJTVGdWsHAcwufhmvSuzr9FSPFCSrgH3',
    '23UKWLdRNPRnm9bqkZPiX5rm4GDmfC8QkpL6vKYSVrgZccbBC7Rd2wppzY32LxoPZRsCjYNYYDZVBybqLiHL2LvGSxKHS6rokWAsS4aZ6ikmMpQv6KQWhCRxh89j1HPeeBAb',
    '24kKm741oCpQti9uWCStQpHHwvS9wR5iBy3dUtdEodVCDhiuUbvPrAbtL3ByaUFCBjhReL6torQvS9ZknbrooV5q5D4xJkUoM3nzjGK6YaryqRwPVKYqnTsDEYBanWKETbEc',
    'or3u1YxTwqsDYpJoJvSTaAPUZywiXsvZasKQdvuy5giBFgxhKCUFRTzRBtgCFRpTapSPNNPG9tbmytTtYWyXNKJBYw46z5P213AqbknGhgTxVg4xsHbosauSwUdU5pRZvkU',
]

[[balance]]
address = '5i9RZjT87TLa1BtWXRRoFy3FoMzFHiXT3GWasHdUaxuo3YapUKYeXXiY1yuAeKng2hmxxaYsGNhKhjyrE9KYTSE7'
seed = 0xdead_beef
notes = [1_000_000_000_000]

[[balance]]
address = 'dQgpVd2XwtXfVhDBdKX5rnXqyRkYsJgZ5wq826wdn6atfKnaNyptTogEko2u2ZWhW5sGADhR4YMKztqrFJphuMz'
seed = 0xdead_beef
notes = [500_000_000_000_000_000]


[[stake]]
address = 'rm6jwcM9xQChnVeHYw6W8HP7kW3E8nejgs4XhmKoYspQnrZL5dDcQjVR5e2UmbyNNF4DJDRdZGdYLgJfZ3qQXuhSCL6UTDkcQ2QEf6RW3aCtfqQMKCFMNaBsfNrZuzrP23Z'
amount = 500_000_000_000_000

[[stake]]
address = 'uazLgN2HtLqaDZCxAtJtkkurQTXyZWXjQYJ3HdSVbpBjGRzMvKaqvpx3MRw8HTv7bTwyviLosEJAa56G66cdNjL4CJdqTUyFHdufzWWfLz9E7eF97tdc6jZsVTiGXGNGf2E'
amount = 500_000_000_000_000

[[stake]]
address = '23RRcwBV2BsBVvmNPUh16xCYfLZj7qkxjCFg8dS5hkJcRrnVbFr5sHHGvTYbcvyDaZ19D6jqn21miC52y9rjycYrG1EBtc1wYwZLhZLHk63L52aaYYoyJtgM6hbuzmPXVvaQ'
amount = 500_000_000_000_000

[[stake]]
address = 'xxRf7HtmFrcNqF8QpEpXmNqEePC7ftcrAGyavJQUv5mQrZKmS1GBazS1fbrftFbj5t6A19F4FComuyLcS9dVkgu8bE7vzA4QTfEUWWjLU9As9FaazE8ewVEBkAe4f8SeGny'
amount = 500_000_000_000_000

[[stake]]
address = 'uZvKUYkVz7SJkicS4gQXGAjj8rziVkcV7ZXqGJAKNSW7iFFfTYCdo3k9Hw4A5dPfUxvBDtBPiSDjmehZGEQwDSYkdSf39WDEbavq9XHyzLY1S72EXCbEoB38avxaY7eXp6i'
amount = 500_000_000_000_000

[[stake]]
address = '22z7SEfWy7VEZqi3Ru6MDzBtHmZWnizPW57t2CHGESLGeuamJ1v4prqPHHrjUkQNW4wJ8mA4nNgRHg1MJdMpmbrar4sMisr5b6tKCCUPvu7hFkKPEP2cdXZkdEUXivx6fjAh'
amount = 500_000_000_000_000

[[stake]]
address = 'uqMkRzvvPL3V3uG2AsZ4M31G4d2tkCRVFEcaeCt2AQpKcFKb9x9Bxa7xTYQsErRp4TsJP5DWyWsPLimTMvGqXXGJEh3aeCYemzD1rwNBQ3fbfD6YHt8T9cLH7MjeAQt9RQv'
amount = 500_000_000_000_000

[[stake]]
address = 'or3u1YxTwqsDYpJoJvSTaAPUZywiXsvZasKQdvuy5giBFgxhKCUFRTzRBtgCFRpTapSPNNPG9tbmytTtYWyXNKJBYw46z5P213AqbknGhgTxVg4xsHbosauSwUdU5pRZvkU'
amount = 500_000_000_000_000

[[stake]]
address = '23YLXnqMDSS7Dts6MtsaMazUChUaZdCJczJT7jSKweAQ5L9KTYqCUGPWMPMBGxSCgGWPkmEvuezJ5RJiBxABGCQmbopxti7voJySHZU9yy6wBqrvnw9pTnFLbSksYgU9DzP8'
amount = 500_000_000_000_000

[[stake]]
address = '21323yLXTiWyRy1nekrjmzaVfJNcpDYWaNWww5yC3ATqR4xQ8hcE5aRbHLzDcBfsGBmd9VhuLsKMLydQpv5gsprn2LrZNBus3x2vDbAWVRMaazehrNvP8C92uSspPjvDdxtd'
amount = 500_000_000_000_000

[[stake]]
address = 'qFDZZfE9SiADC9s4wAy9mdFHHf4FhG9qZwDd7zx4SAu1s7kjoxgCbMDe6kN2J3QUFE2PPvBJttRhhz8nsWBKL4kRxWwEda2TY7kYKkkBF8NCQiquvB39cqb9Qwi2QHXHcWD'
amount = 500_000_000_000_000

[[stake]]
address = '24kKm741oCpQti9uWCStQpHHwvS9wR5iBy3dUtdEodVCDhiuUbvPrAbtL3ByaUFCBjhReL6torQvS9ZknbrooV5q5D4xJkUoM3nzjGK6YaryqRwPVKYqnTsDEYBanWKETbEc'
amount = 500_000_000_000_000

[[stake]]
address = '24ED5zGePkU2Tfpp3X1NxSFhhgNCYBakorBJCXEhwVeWwB341XY9Xk2cJ5uhQ8TAHXGyJAE4EZakhWFkPy1vRr7moR8A9q47P5kkTzo7pWqggog5Lpjvkko2FJwKNJJRG9mc'
amount = 500_000_000_000_000

[[stake]]
address = '23wQuNYp2dL9BcnFNnizSBnxjhHerR6WjYFNLS6qmM3KNvf1Gia27u3Vkjg88jCwvwwTSHWpEDCX9NojejCKZ25HvZLaDeLrfkL2wCXFXz5GT44QGFyQqM9uN2taNjPVBTkN'
amount = 500_000_000_000_000

[[stake]]
address = 'nhkM2nfamRmrgoGa8JYnfaL6tavSY7qRrduY1dG1NiQtLyqALHz9XtAqbhuuR57q9oTVgqb5TdvBrKwm5gYH2zLjSwrq7C4gYwS7bDRqhM4ZogawoJmteKSAMPWqT6EK3rn'
amount = 500_000_000_000_000

[[stake]]
address = 'sQf2dezLcqZus4mh5KfB5keeF2FQeoXyA2ABzgDNr2B2dS1dq87ueUFNHyKy3DcM7qw748T68PSkpAXkmbbzCoMT7FdKuMnM1Ht729GjgtBqUdgPVjNZPuE9MqSxwtrjnpw'
amount = 500_000_000_000_000

[[stake]]
address = '212Eszgyh7GqMTwspNw4jhT4eFdhM281jLXV6CKyF7Yyh8DAv45XL9iszYnVArAYQdBP72jZkvMZE1gmnY1PJgo4S2uvx5ann9iHUyTfHxU9MBti2M9ymytqQbBc3vpDEd81'
amount = 500_000_000_000_000

[[stake]]
address = '2232sf7xouh6x9geCQCXjGBf57ezX274ZS5R2MY68UXvu6BQP6aUbVNcWQgWzJo47q86AonZiJePKUwbGzp5VDudMKpmxS333Vn3N6GHtJA5w3xG5wiY7XfXix1XwXS53ECm'
amount = 500_000_000_000_000

[[stake]]
address = 'yobLCBgyyZhk5Gb3t6StQHSPWXb8Cf3U5ueShEgEtU8zCVSDTq9ZHqvjY6Mu1WA9N4LUjYWrm95Mb4C7VRUwEHEhXfpyqVdbhvsLiRjuiAbun2AUe4FRwWZk1DR3QdYKc9Q'
amount = 500_000_000_000_000

[[stake]]
address = '23KjUiz6qUEUquZdJN3C8owXWYZSaRfuB6nM312QmvjQgGYVfijCqiyFY49PneqpvBayxYpz1CLFHjktqZwdtTStJHZXSmMooKdyLyZA8fy3ffGqp7JYTkZABiiY8NeozroF'
amount = 500_000_000_000_000

[[stake]]
address = '26urMnP7s57oyDYChtPoxVH8UbW2cRNeCXPduv3NCQ3E5syWK2fpPVS31fvDbMVR5b71WWktDCJGpeCFEAK14TKcn7YJxUoYASmQsfpvd3WcmtPoG6muA7LXKL4zZYstCZEV'
amount = 500_000_000_000_000

[[stake]]
address = '213uCMVTh44twwWxV1q2X7yKWDG4VXGrDGo2Sb8GzNWVQTaext61Po21pFcPpJPFuYqkqqTxyTjeZJkwL5GkwKDWe78HTyYCh6w5RYtp2bJeikqGXkabbc34xYYLc3y7F5BA'
amount = 500_000_000_000_000

[[stake]]
address = 'mZAnxKrBuBm8Bgfr6PobgwHFNsb2VcibPqDz9GxjABZB9J7wJYidkCBdnDwoPZXj7Gjut8a978ADdVooutRH6XH2zvtx6S8EH3Ax8WFFCjHEkxK1wisKW5bb5tWYgkQA6jK'
amount = 500_000_000_000_000

[[stake]]
address = 'pedJJvzh9GuUQXE39JUZPnQkUahXoPeuVDUK1MAqN5WTsHViukdKd4QinGNtqY7VQyRYQKNYDsY7pqUV89bvAGyeHjF1XC6rKhUhsYuWBHqhizcxpjc5cpLfH1vb62ZGXZs'
amount = 500_000_000_000_000

[[stake]]
address = 'qEw65a4i3J7bYeFMdV5agXzKaw44v3eWyXjoer3nZqou6uF8ve7fFCFpVLhgdooE4LDjT48xnihtYKypzbKzDMWzPXb5Vrrjspo37WSfUSYD3VhtL61eDNUp7vBqaYP3Q25'
amount = 500_000_000_000_000

[[stake]]
address = 'npbMNQM1xKYsxzrBx5bXDmCC3DKPDyw6WKYnHQ1C8tDJcDLtkNQGSU7GEoM1NUAoap5pJHXzxo3MAt8VDXxKAYg5qSPZjbSFwYJofX16HQooQbFBDF5Ubx6jPso5uVAt5Wq'
amount = 500_000_000_000_000

[[stake]]
address = 'ncx72nK92RJT1QAV71DaPwNtV7LAZDiWNu7gCennDZkfXyjh6bRiB3az2CL9St8aFB3tLatZ22n2FvoVfVtvLrtKLtmScaupQmPnkxeLj8UEpRX89oP9Rm1h4msVzFyQ4n1'
amount = 500_000_000_000_000

[[stake]]
address = '26URNquMJ4ZxbBz9C75zC9ExUHHH9NFSc1XVi8FGwLwtTfXw7f9qwnUknTKR53YCfCPF5hTSNuM1iX8Q3bgMVmEotBf9CK3zHNa2HPWa1XRmkbkoN4A4vyUEaWDQLM7ionEP'
amount = 500_000_000_000_000

[[stake]]
address = 'm8AHSke1BAZPVBrkLjGEQXhfhpzD7yfd95bfY96LqiJdyuCVc16qpHYe3JX7Uq8FzwvsCKvkvMeXyAKCkVNsPvy7uExY9XNTF8hQbXDf71AEEu94Fc4EPTmFBLYG6TQAMEo'
amount = 500_000_000_000_000


[[stake]]
address = '22GNXdXKRebsro2FiZsSvFuxCTBzDmvuMQzEBKN81ZK2RJg1wkFaFtaqSF4ooPqDGd5n7Phq4CSwt3YcBPKFKoCNiGNCrApw861hPpdQ8NcNq3MBJ6KTXMqTMSjoBNeMsgZj'
amount = 500_000_000_000_000
