[package]
name = "transfer-wrapper"
version = "0.1.0"
authors = ["Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
canonical = "0.6"
canonical_derive = "0.6"
dusk-abi = "0.9"
rusk-abi = { path = "../../rusk-abi" }
dusk-bytes = "0.1"
dusk-bls12_381 = { version = "0.8", default-features = false, features = ["canon"] }
dusk-jubjub = { version = "0.10", default-features = false, features = ["canon"] }
dusk-poseidon = { version = "0.23.0-rc", default-features = false, features = ["canon"] }
dusk-pki = { version = "0.9.0-rc", default-features = false }
phoenix-core = { version = "0.15.0-rc", default-features = false, features = ["canon"] }
dusk-hamt = { version = "0.5.0-rc", default-features = false }
microkelvin = "0.10"
lazy_static = "1.4"
rand = "0.8"
transfer-circuits = { path = "../../circuits/transfer", features = ["builder"] }
transfer-contract = { path = "../../contracts/transfer" }
rusk-profile = { path = "../../rusk-profile" }
dusk-plonk = "0.9"
rusk-vm = "0.7.0-rc"
