[package]
name = "stake-contract-types"
description = "Stake contract types for the Dusk Network."
version = "0.0.1-rc.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
dusk-bls12_381 = { version = "0.12", default-features = false, features = ["rkyv-impl"] }
dusk-bls12_381-sign = { version = "0.5", default-features = false, features = ["rkyv-impl"] }
dusk-pki = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"

rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
