[package]
name = "transfer-circuits"
version = "0.2.0"
authors = ["Bounce23 <luke@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
rand_core = "0.5"
anyhow = "1.0"
dusk-bytes = "0.1"
dusk-plonk = "0.5"
canonical = "0.5"
phoenix-core = {git="https://github.com/dusk-network/phoenix-core", tag="v0.7.2", features = ["canon"]}
poseidon252 = {git="https://github.com/dusk-network/Poseidon252", tag="v0.17.0", features=["canon"]}
dusk-pki = {git="https://github.com/dusk-network/dusk-pki", tag="v0.5.1"}
schnorr = {git="https://github.com/dusk-network/schnorr", tag="v0.4.0"}
rusk-profile = {path="../../../profile", optional=true}
canonical_derive = {version="0.5", optional=true}

[dev-dependencies]
canonical_derive = "0.5"
rand = "0.7"
canonical_host = "0.5"
rusk-profile = {path="../../../profile"}

[features]
builder = ["canonical_derive", "rusk-profile"]
builder-no-rusk-profile-keys = []
